### ISSUE TITLE
[BUG] Polyglot incompatible with Monk's Enhanced Journal

### ISSUE THREAD

**Issue by rtschaefer** [ironmonk88/monks-enhanced-journal#419]
**Describe the bug**
Polyglot menu option does not appear whenever I activate Monk's Enhanced Journal. When I deactivate the module, then Polyglot works as it is supposed to. 

**Please complete as much of the following information as possible:**
 - Browser: Chrome Version 106.0.5249.119 (Official Build) (64-bit)
 - Foundry Version:  v10, build 288
 - System:  D&D5e
 - Module version: 10.4

**Comment by Truncated** [comment]
Note: On Foundry V10, the Journal features don't work on the ProseMirror editor (the default editor). If you want to use this feature, you must change the Sheet to TinyMCE.

Source: https://clemente.gitbook.io/polyglot/how-to-use/journal

**Comment by ironmonk88** [comment]
Should be fixed in the latest release

**Comment by Kurokasa** [comment]
Its still not working, when both modules are active no journals can be edited by a Player (GM side seems to be working).

Browser: Chrome Version
Foundry Version: v10, build 290
System: D&D5e
Module version: 10.5

![Screenshot 2022-11-22 090312](https://user-images.githubusercontent.com/102412559/203259954-d5346351-3eb8-4136-a1a4-b1dedff85889.jpg)
