### ISSUE TITLE
[BUG] Using the default journal entries, when placing a sub-page as a journal note on the map, the link does opens to the entire entry, not specifically at the sub-page

### ISSUE THREAD

**Issue by Mermut** [ironmonk88/monks-enhanced-journal#440]
Using the default text journal, make an entry with multiple pages.
Drag page 2, 3, etc (anything other than 1) to the map as a map pin/journal entry.
Click on the entry on the map.
The Journal opens to page 1, not the page actually dragged onto the map.

Note: The description of the pin on the map matches the page dragged onto the map. The link doesn't go directly to it, however.

This is new behavior since the update on 11/19/2022

Additional related note: Adding more 'pages' to the default text journal entries is adding the new page at the 'top'  of the journal list not the bottom.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release

**Comment by Mermut** [comment]
I'm still seeing the problem.
Even when tested in a world with this as the only module.

**Comment by Crowguard** [comment]
Can confirm it's still happening in MEJ 10.6.

https://user-images.githubusercontent.com/99844555/206519757-e1935077-f863-4958-a1bd-bd93387d6022.mp4

This error only occurs when you're on the 1st page of a journal and attempt to open the note; any other page is errorless.

![image](https://user-images.githubusercontent.com/99844555/206519925-cea50e59-62ed-499b-8cfa-3ce1ff815a9b.png)

Foundry 10.291
D&D 2.0.3
MEJ 10.6

**Comment by jgnoel86** [comment]
Hi Monk, I was running into this issue as well, and what resolved it for me is line 187 of apps/enhanced-journal.js

Changing the merge that happens to the options within the renderSubSheet method from:
`options = mergeObject(options, game.user.getFlag("monks-enhanced-journal", `pagestate.${this.object.id}`) || {});`

To 

`            
if(!options.pageId)
     options = mergeObject(options, game.user.getFlag("monks-enhanced-journal", `pagestate.${this.object.id}`) || {});
`

js is not my first language C++ is, nor do I pretend to know the entirety of this module, but hopefully this will help you solve the issue properly if my tweak doesn't work universally.
