### ISSUE TITLE
[BUG] Bookmark Warning

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#481]
Occurs when pressing the star button to bookmark a tab.

![image](https://user-images.githubusercontent.com/99844555/213344870-c9547cd4-556f-44cb-8709-8b3b999e7a3e.png)

MEJ 10.12
Foundry 10.291

**Comment by ironmonk88** [comment]
I think I fixed this.
I'll get confirmation on the next release.
Should only be flagged for Actor sheets.

**Comment by Crowguard** [comment]
Still happening, not just with actor sheets.
https://user-images.githubusercontent.com/99844555/218538552-ef5bf287-ce54-4ca9-934d-02ee7fa22ccc.mp4

MEJ 10.14

**Comment by ironmonk88** [comment]
Fixed in the latest release
