### ISSUE TITLE
[BUG] monks-enhanced-journal not working in V11

### ISSUE THREAD

**Issue by QuestionQuest117** [ironmonk88/monks-enhanced-journal#567]
**Describe the bug**
monks-enhanced-journal is not working in Foundry V11, especially in presence of lib-wrapper

**To Reproduce**
1. Update Foundry to V11
2. Launch D&D5e world
3. Activate monks-enhanced-journal and lib-wrapper
Issues should still be found with only monks-enhanced-journal active

**Expected behavior**
monks-enhanced-journal does not appear active as there are no tabs, an error message appears along the top, and lib-wrapper absolves itself of any wrongdoing in the logs.

**Screenshots**
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/54755301/345f8e64-9d4c-444a-b5cd-ce40fafeb234)
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/54755301/82120eb7-6343-4162-8b6b-7b3bc5aedfb6)

**Please complete as much of the following information as possible:**
 - Browser Foundry Native Application
 - Foundry Version V11
 - System D&D5e
 - Module version: 10.14
 - Are there any errors in the console: Yes
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: Yes. It doesn't like lib-wrapper, but lib-wrapper swears it isn't the problem (and lib-wrapper has worked fine in previous Foundry versions) and monks-enhanced-journal doesn't work even with lib-wrapper disabled.

**Additional context**
Uncaught (in promise) LibWrapperPackageError: lib-wrapper. Error detected in module Monk's Enhanced Journal. It is likely this module has not been updated for FVTT Version 11 Stable.

This is *not* a libWrapper bug.

Find information about this module here: https://github.com/ironmonk88/monks-enhanced-journal
Report this issue here: https://github.com/ironmonk88/monks-enhanced-journal/issues

== Technical Details:
Detected by libWrapper.
Package ID= monks-enhanced-journal
Error= Can't wrap 'JournalDirectory.prototype._onClickDocumentName', target does not exist or could not be found.

[Detected 2 packages: lib-wrapper, monks-enhanced-journal]
    at new 🎁constructor (libWrapper-wrapper.js:111:11)
    at libWrapper-api.js:82:18
    at de (libWrapper-api.js:155:9)
    at 🎁register [as register] (libWrapper-api.js:525:14)
    at MonksEnhancedJournal.init (monks-enhanced-journal.js:329:24)
    at Object.fn (monks-enhanced-journal.js:3525:26)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.initialize (foundry.js:8529:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁libWrapperInit (libWrapper-api.js:805:11)

**Comment by EvldoaTV** [comment]
I am also having this same issue with enhanced journal and shop

**Comment by spidermoiz** [comment]
having the same issues here, same errors, not working and all shops stopped working
basically every enhanced journal is either not working or completely broken. 

please help

**Comment by Crowguard** [comment]
MATT & MEJ are not yet V11 compatible. Stop upgrading versions if the modules you depend on are not updated yet.

**Comment by iammythhunter** [comment]
Would like to bump this, just because Monk's are the last modules I need for the update. Not a bug, obviously, just a compatibility break.
As far as people updating before ready, for sure, important not to do that. No module is guaranteed to continue to work after a Foundry update.

**Comment by Digit4** [comment]
This is fixed with the latest update, I've tested it myself. I would suggest closing this issue once you've tested it.

**Comment by flufflesamy** [comment]
Issue still persists even with latest update 
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/7064314/7c858d3c-3f76-41a5-a697-47c54b263187)
Using latest update:
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/7064314/214868e2-5d16-4bb7-bcd9-685072184ccc)

**Comment by Antelbxl** [comment]
Still not working for me.
Game system: Runequest Glorantha Foundry VTT system by sun-dragon-cult on Github.

The system forced me to upgrade to V11. 
I can't go back, so the compatibilty issue is a real problem for me. I'll have to uninstall this mod...

**Comment by ironmonk88** [comment]
Closing this as it should be fixed by now.
